sudo: required

services:
  - docker

stages:
  - build

env:
  global:
    - IMAGE_NAME=steamcmd
    - TAG_GIT=git
    - TAG_MINIMAL=minimal

before_script:
  # Registry login(s)
  - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

script:
  - date
  - docker build
    -t "${REGISTRY_USER}/${IMAGE_NAME}:latest"
    -t "${REGISTRY_USER}/${IMAGE_NAME}:${TAG_GIT}"
    "${TAG_GIT}/"
  - docker build
    -t "${REGISTRY_USER}/${IMAGE_NAME}:${TAG_MINIMAL}"
    "${TAG_MINIMAL}/"
  - docker images

  # Push the image
  - docker push "${REGISTRY_USER}/${IMAGE_NAME}"

after_script:
  - docker logout