language: bash
services: docker

env:
  global:
    - IMAGE_NAME=steamcmd

before_script:
  - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

script:
  - date

  - docker build
    -t "${REGISTRY_USER}/${IMAGE_NAME}:${TAG}"
    "${TAG}/"
  - if [ "$LATEST" = true ]; then
      docker tag "${REGISTRY_USER}/${IMAGE_NAME}:${TAG}" "${REGISTRY_USER}/${IMAGE_NAME}:latest";
    fi
  - docker images

  # Test the image
  - if [ "${NO_TEST_RUN}" != true ]; then
      docker run --rm "${REGISTRY_USER}/${IMAGE_NAME}:${TAG}" /bin/bash -c "printenv && ls -al && exec steamcmd.sh +login anonymous +quit";
    fi

  - docker push "${REGISTRY_USER}/${IMAGE_NAME}"

after_script:
  - docker logout