language: bash
services: docker

env:
  global:
    - IMAGE_NAME=steamcmd

before_script:
  - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

script:
  - date

  - docker build
    -t "${REGISTRY_USER}/${IMAGE_NAME}:latest"
    -t "${REGISTRY_USER}/${IMAGE_NAME}:${TAG}"
    "${TAG}/"
  - docker images

  - docker push "${REGISTRY_USER}/${IMAGE_NAME}"

after_script:
  - docker logout