name: build

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        BASE_IMAGE_NAME: [ubuntu]
        BASE_IMAGE_TAG: [xenial-20181005]
        BUILD_IMAGE_VARIANT: [git, minimal]
        include:
        - BASE_IMAGE_TAG: xenial-20181005
          BUILD_IMAGE_VARIANT: git
          TAG_LATEST: true
    env:
      BASE_REGISTRY_NAMESPACE: library
      BASE_IMAGE_NAME: ${{ matrix.BASE_IMAGE_NAME }}
      BASE_IMAGE_TAG: ${{ matrix.BASE_IMAGE_TAG }}
      BUILD_REGISTRY_NAMESPACE: startersclan
      BUILD_IMAGE_NAME: steamcmd
      BUILD_IMAGE_VARIANT: ${{ matrix.BUILD_IMAGE_VARIANT }}
      TAG_LATEST: ${{ matrix.TAG_LATEST }}
    steps:
    - uses: actions/checkout@v1
    - name: Build, test, push image
      run: |
        export RELEASE_TAG_REF=$(echo "${GITHUB_REF}" | sed -rn 's/^refs\/tags\/(.*)/\1/p')
        ./build.sh
      env:
        DOCKERHUB_REGISTRY_USER: startersclan
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
