name: build

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        OS: [ubuntu]
        OS_ARCHIVE: [xenial-20181005]
        TOOL_VARIANT: [git, minimal]
        include:
        - OS_ARCHIVE: xenial-20181005
          TOOL_VARIANT: git
          TAG_LATEST: true
    env:
      OS: ${{ matrix.OS }}
      OS_ARCHIVE: ${{ matrix.OS_ARCHIVE }}
      TOOL_VARIANT: ${{ matrix.TOOL_VARIANT }}
      TAG_LATEST: ${{ matrix.TAG_LATEST }}
      BASE_REGISTRY_NAMESPACE: library
      BUILD_REGISTRY_NAMESPACE: startersclan
      BUILD_IMAGE_NAME: steamcmd
    steps:
    - uses: actions/checkout@v1
    - name: Build, test, push image
      run: |
        export TAG_TOOL_ARCHIVE=$(echo "${GITHUB_REF}" | sed -rn 's/^refs\/tags\/(.*)/\1/p')
        ./build.sh
      env:
        DOCKERHUB_REGISTRY_USER: startersclan
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
